config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  post 'signup',   to: 'sessions#create'
  get  'signup',   to: 'sessions#new'
  get  'signout',  to: 'sessions#destroy'
  resources :customers#, only: [:show, :index, :create, :new, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base_customer.rb
class BaseCustomer < ApplicationRecord
  include ParamsExtendable
  has_secure_password
  belongs_to :extension, polymorphic: true
  validates :name, presence: true, uniqueness: true

  def self.extend_base_customer(col_name, type)
    ActiveRecord::Schema.define do 
      change_table :base_customers do |t|
        t.column col_name.to_sym, type.to_sym
      end
    end
  end

  def self.create_with_extension(attributes)
    sub = nil
    Extension.constants.select{|c| Extension.const_get(c).is_a? Class}.map do |ext|
      sub = "Extension::#{ext}".constantize.new
      if sub.attribute_names | self.extension_attributes_to_s(attributes) == sub.attribute_names
        self.extension_attributes_to_s(attributes).map do |key|
          sub.send("#{key}=", attributes[key.to_sym])
        end
        sub.save!
        sub.create_base_customer!(name: attributes[:name], phone: attributes[:phone],password: BCrypt::Password.create(attributes[:password]))
      end
    end
    sub
  end

  def self.extension_attributes_to_s(attr={})
    attr.except(:name,:phone, :password).keys.map(&:to_s)
  end
end

app/models/extension/bar_customer.rb
module Extension
class BarCustomer < ApplicationRecord
  has_one :base_customer, as: :extension
  #attr_accessor :hometown, :make, :model
end
end

app/models/extension/foo_customer.rb
module Extension
class FooCustomer < ApplicationRecord
  has_one :base_customer, as: :extension
  #attr_accessor :email
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
    add_flash_types :error
end

app/controllers/concerns/authable.rb
module Authable
  extend ActiveSupport::Concern
  def http_auth
    authenticate_or_request_with_http_basic do |username,password|
     @base = BaseCustomer.find_by(name: username).try(:authenticate, password)
    end
  end
end

app/controllers/concerns/params_extendable.rb
module ParamsExtendable
  extend ActiveSupport::Concern

  def specific_params
    self.as_json.except("created_at", "updated_at", "password_digest")
  end
end

app/controllers/concerns/responsible.rb
module Responsible
  def json_response object, status=200
    render json: object, status: status
  end
end

app/controllers/concerns/sessionable.rb
module Sessionable 
  extend ActiveSupport::Concern

  def login customer
    session[:customer_id] = customer.id
  end

  def logout
    session.delete(:customer_id)
    @current_user = nil
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  include Responsible
  include ParamsExtendable
  include Sessionable
  include SessionsHelper

  #before_action :http_auth
  before_action :current_user, only: [:index, :show, :update]

  def index
    @customers = BaseCustomer.includes(:extension).where(extension_type: @current_user.extension_type)
      .map{|c| c.as_json.merge(c.extension.as_json){|key,a,b|a}.except("created_at","updated_at", "password_digest")}
    #json_response @customers, 200
  end

  def show
    @customer = BaseCustomer.includes(:extension).find_by(extension_type: @current_user.extension_type)
  end

  def create
    @customer = BaseCustomer.new customer_params
    if @customer.save
      redirect_to customer_index_path
    else
      flash.now.alert = "Saving failed. Try again"
      redirect_to customer_new_path
    end
  end

  def new 
    @customer = BaseCustomer.new
  end

  def edit
    @customer = BaseCustomer.where(id: params[:id]).first
  end

  def update
    # update only spec attributes
    # not override them with empty param keys -as it would be now
    @customer.update_attributes params[:base_customer]
    @customer.extension.update_attribute extended_params
  end

  private 
  def extended_params
    attr = self.extension.attributes.keys - ['id','updated_at','created_at']
    params.require(:base_customer).permit(:name, :phone, :batt_cap, extensions: attr)
  end

  def customer_params
    params.require(:base_customer).permit(:name, :batt_cap, :phone, :password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include Sessionable
  
  def create
   # authenticate_or_request_with_http_basic do |username,password|
     customer = BaseCustomer.find_by(name: params[:session][:name]).try(:authenticate, params[:session][:password])
     if customer.present?
       login customer
       redirect_to customers_path
     else
       render :new
    end
  end
  
  def destroy
    logout
    redirect_to root_path
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= BaseCustomer.find_by(id: session[:customer_id]) if session[:customer_id]
  end
end

app/views/customers/create.html.erb
<h1>Customer#create</h1>
<p>Find me in app/views/customer/create.html.erb</p>

app/views/customers/destroy.html.erb
<h1>Customer#destroy</h1>
<p>Find me in app/views/customer/destroy.html.erb</p>

app/views/customers/edit.html.erb
<h1>Customer#update</h1>
<p><%= link_to "Log out", signout_path %></p>

<%= form_with model: @customer, url: customer_path do |f| %>
  <%- @customer.specific_params.keys.map(&:to_sym).each do |el| %>
  <%= f.label el  %>
  <%= f.text_field el, class: 'form-control' %>
  <br>
<%- end %>
<%- @customer.extension.attributes.keys.map(&:to_sym).each do |el| %>
  <%= f.label  el %>
  <%= f.text_field el, class: 'form-control' %>
  <br>
<% end %>
<%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>

app/views/customers/index.html.erb
<style type="text/css">
table {
    border-collapse: separate;
    border-spacing: 0;
    text-align: center;
}
th,td {
    padding: 10px 15px;
}
thead {
    background: #395870;
    color: #fff;
}
tbody tr:nth-child(even) {
    background: #f0f0f2;
}
td {
    border-bottom: 1px solid #cecfd5;
    border-right: 1px solid #cecfd5;
}
td:first-child {
    border-left: 1px solid #cecfd5;
}
</style>
<h1>LandingPage</h1>
<p>You are a type <%= current_user.extension_type.split('::').last %> Customer </p>
<p>You only see Customers form the same kind. </p>
<%= link_to "Log out", signout_path %>
<table>
  <caption> Specific Customer Table </caption>
  <thead>
  <tr>
<% @customers.first.keys.each do |key| %>
  <th scope="col"> <%= key%> </th>
<% end %>
  </tr>
  </thead>
<% @customers.each do |c| %>
  <tbody>
  <tr>
    <%- c.keys.each do |key|%>
      <%- if key == "name" %> 
        <td><%=  link_to c[key], customer_path(BaseCustomer.find_by_name(c[key])) %></td>
      <%- else %> 
        <td><%=  c[key] %></td>
      <% end %>
    <% end %>
  </tr>
<% end %>
</table>
</tbody>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= form_for :base_customer, url: customer_create_path(@customer) do |f| %>
<div>
<%= f.label :name %>
<%= f.text_field :name, autofocus: true %>
</div>
<div>
<%= f.label :phone %>
<%= f.text_field :phone %>
</div>
<div>
<%= f.label :batt_cap %>
<%= f.text_field :batt_cap %>
</div>

<div>
<%= f.label :password %>
<%= f.password_field :password %>
</div>
<div>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
</div>
<div>
<%= f.submit "Submit" %>
</div>
<% end %>

app/views/customers/show.html.erb
<style type="text/css">
  table, th, td {
    border: 1px solid black;
    padding: 10px;
  }
</style>

<h1>Customer <%= @customer.name %> </h1>
<p> <%= link_to "Log out", signout_path %> </p>
<p> <%= link_to("Update Customer", edit_customer_path(@customer), :method => :put) %> 
<table >
<tbody>
  <%- @customer.as_json.merge(@customer.extension.as_json){|k,a,b| a}.keys.map do |k| %>
  <tr>
    <td><%= k %></td>
    <td><%= @customer.attributes[k] %></td>
  </tr>
<% end %>
</tbody>
</table>